### ISSUE TITLE
Vulnerability in event-stream dependency

### ISSUE THREAD

**Issue by manojvignesh** [mikehazell/gulp-inject-string#14]
dominictarr/event-stream#116

Update event-stream dependency to event-stream@3.3.4 per

**Comment by evanre** [comment]
Hi, I'm afraid it's abandoned. I'm waiting for approving my PR since June.

**Comment by manojvignesh** [comment]
It's problem coz this package has a weekly downloads of 6,719. I've changed to gulp-inject anyway.
I'll leave this open anyway...

**Comment by brunocalderon** [comment]
@evanre @manojvignesh I think the same, i reported the package to NPM, hope they will yank it.

**Comment by mikehazell** [comment]
This was resolved in #15
